[profile.default]
src = "src"
out = "out"
libs = ["dependencies"] 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
"@openzeppelin-contracts" = "5.3"
"@aurora-sdk" = { version = "0.1.0", git = "https://github.com/aurora-is-near/aurora-contracts-sdk.git", tag = "v0.1.0" }
forge-std = "1.9"

[soldeer]
recursive_deps = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
