[profile.default]
src = "src"
out = "out"
libs = ["dependencies"] 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
forge-std = "1.9.7"

